// Host test for midea AC command builders (GetState/SetState/GetCapabilities/
// ToggleDisplay) against golden
// frames generated by msmart itself (vectors/commands.txt), plus counter and
// buffer-edge cases. Vectors pin Command._message_id per build; the test resets
// the C++ counter to match before each serialize().
#include "Commands.h"
#include "Crc8.h"
#include "Frame.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace {

int hexNibble(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

bool parseHex(const std::string& hex, std::vector<uint8_t>& out) {
  if (hex.size() % 2 != 0) return false;
  out.clear();
  out.reserve(hex.size() / 2);
  for (size_t i = 0; i < hex.size(); i += 2) {
    const int hi = hexNibble(hex[i]);
    const int lo = hexNibble(hex[i + 1]);
    if (hi < 0 || lo < 0) return false;
    out.push_back(static_cast<uint8_t>((hi << 4) | lo));
  }
  return true;
}

using Fields = std::unordered_map<std::string, std::string>;

// Parses the shared vector format: column-0 name, indented `field value`.
std::vector<std::pair<std::string, Fields>> loadVectors(const char* path) {
  std::vector<std::pair<std::string, Fields>> vectors;
  std::ifstream file(path);
  if (!file) {
    std::printf("FAIL: cannot open %s (run from test/host dir)\n", path);
    return vectors;
  }
  std::string line, name;
  Fields fields;
  bool have = false;
  while (std::getline(file, line)) {
    if (line.empty() || line[0] == '#') continue;
    if (line[0] != ' ') {
      if (have) vectors.emplace_back(name, fields);
      name = line;
      fields.clear();
      have = true;
      continue;
    }
    std::istringstream kv(line);
    std::string key, value;
    if (kv >> key >> value) fields[key] = value;
  }
  if (have) vectors.emplace_back(name, fields);
  return vectors;
}

unsigned gFailures = 0;

void check(bool ok, const std::string& what) {
  std::printf("%s %s\n", ok ? "ok  " : "FAIL", what.c_str());
  if (!ok) ++gFailures;
}

uint8_t fieldHex(const Fields& f, const char* key) {
  return static_cast<uint8_t>(std::strtoul(f.at(key).c_str(), nullptr, 16));
}
uint8_t fieldU8(const Fields& f, const char* key) {
  return static_cast<uint8_t>(std::strtoul(f.at(key).c_str(), nullptr, 10));
}
bool fieldBool(const Fields& f, const char* key) {
  return f.at(key) == "1";
}
bool fieldBoolDefault(const Fields& f, const char* key, bool fallback) {
  const auto it = f.find(key);
  return it == f.end() ? fallback : it->second == "1";
}
uint8_t fieldU8Default(const Fields& f, const char* key, uint8_t fallback) {
  const auto it = f.find(key);
  return it == f.end() ? fallback : fieldU8(f, key);
}
double fieldDouble(const Fields& f, const char* key) {
  return std::strtod(f.at(key).c_str(), nullptr);
}

std::string toHex(const uint8_t* data, size_t len) {
  static const char* kHex = "0123456789abcdef";
  std::string s;
  s.reserve(len * 2);
  for (size_t i = 0; i < len; ++i) {
    s += kHex[data[i] >> 4];
    s += kHex[data[i] & 0xF];
  }
  return s;
}

// Shared structural checks every golden frame must satisfy.
void checkFrameShape(const std::string& name, const uint8_t* frame, size_t len, uint8_t counter,
                     uint8_t expectedFrameType) {
  if (len < midea::kFrameHeaderLen + 3) { // header + id + crc8 + checksum minimum
    check(false, name + ": frame too short");
    return;
  }
  check(frame[0] == midea::kFrameStart && frame[2] == midea::kDeviceTypeAc, name + ": start + device type");
  check(frame[9] == expectedFrameType, name + ": frame type");
  check(frame[1] == len - 1, name + ": length byte");
  check(frame[len - 3] == static_cast<uint8_t>(counter + 1), name + ": message id = counter + 1");
  // CRC8 covers data + message id (frame[10 .. len-2)); frame checksum covers
  // everything from byte 1.
  check(midea::crc8(frame + 10, len - 12) == frame[len - 2], name + ": payload crc8");
  check(midea::validateFrame(frame, len, midea::kDeviceTypeAc), name + ": frame validates");
}

void checkFrameEq(const std::string& name, const std::string& got, const std::string& want) {
  if (got != want) {
    std::printf("FAIL %s\n  got  %s\n  want %s\n", name.c_str(), got.c_str(), want.c_str());
    ++gFailures;
  } else {
    check(true, name + ": frame matches golden");
  }
}

} // namespace

int main() {
  const auto vectors = loadVectors("vectors/commands.txt");
  if (vectors.empty()) return 1;

  for (const auto& [name, fields] : vectors) {
    std::vector<uint8_t> expected;
    if (!parseHex(fields.at("frame"), expected)) {
      check(false, name + ": malformed golden frame");
      continue;
    }
    const uint8_t counter = fieldHex(fields, "message_id_counter");
    uint8_t buf[midea::kCommandMaxFrameLen];

    if (fields.count("command")) {
      const std::string& command = fields.at("command");
      size_t len = 0;
      if (command == "get_capabilities") {
        midea::GetCapabilitiesCommand cmd;
        cmd.additional = fieldBool(fields, "additional");
        midea::resetMessageId(counter);
        len = cmd.serialize(buf, sizeof(buf));
      } else if (command == "toggle_display") {
        midea::ToggleDisplayCommand cmd;
        cmd.beepOn = fieldBool(fields, "beep_on");
        midea::resetMessageId(counter);
        len = cmd.serialize(buf, sizeof(buf));
      } else if (command == "get_group_data") {
        midea::GetGroupDataCommand cmd;
        cmd.group = fieldU8(fields, "group");
        midea::resetMessageId(counter);
        len = cmd.serialize(buf, sizeof(buf));
      } else if (command == "get_properties") {
        midea::GetPropertiesCommand cmd;
        cmd.queryIeco = fieldBool(fields, "query_ieco");
        cmd.queryOutSilent = fieldBool(fields, "query_out_silent");
        cmd.querySelfClean = fieldBoolDefault(fields, "query_self_clean", false);
        cmd.queryBreezeAway = fieldBoolDefault(fields, "query_breeze_away", false);
        cmd.queryBreezeless = fieldBoolDefault(fields, "query_breezeless", false);
        cmd.queryFlash = fieldBoolDefault(fields, "query_flash", false);
        cmd.queryRateSelect = fieldBoolDefault(fields, "query_rate_select", false);
        cmd.queryCascade = fieldBoolDefault(fields, "query_cascade", false);
        cmd.queryFreshAir = fieldBoolDefault(fields, "query_fresh_air", false);
        midea::resetMessageId(counter);
        len = cmd.serialize(buf, sizeof(buf));
      } else if (command == "set_properties") {
        midea::SetPropertiesCommand cmd;
        cmd.setIeco = fieldBool(fields, "set_ieco");
        cmd.iecoNumber = fieldU8(fields, "ieco_number");
        cmd.iecoOn = fieldBool(fields, "ieco_on");
        cmd.setOutSilent = fieldBool(fields, "set_out_silent");
        cmd.outSilentOn = fieldBool(fields, "out_silent_on");
        cmd.setSelfClean = fieldBoolDefault(fields, "set_self_clean", false);
        cmd.setBreezeAway = fieldBoolDefault(fields, "set_breeze_away", false);
        cmd.breezeAwayOn = fieldBoolDefault(fields, "breeze_away_on", false);
        cmd.setBreezeless = fieldBoolDefault(fields, "set_breezeless", false);
        cmd.breezelessOn = fieldBoolDefault(fields, "breezeless_on", false);
        cmd.setFlash = fieldBoolDefault(fields, "set_flash", false);
        cmd.flashOn = fieldBoolDefault(fields, "flash_on", false);
        cmd.setRateSelect = fieldBoolDefault(fields, "set_rate_select", false);
        cmd.rateSelectValue = fieldU8Default(fields, "rate_select_value", 100);
        cmd.setCascade = fieldBoolDefault(fields, "set_cascade", false);
        cmd.cascadeMode = fieldU8Default(fields, "cascade_mode", 0);
        cmd.setFreshAir = fieldBoolDefault(fields, "set_fresh_air", false);
        cmd.freshAirSpeed = fieldU8Default(fields, "fresh_air_speed", 0);
        cmd.setBuzzer = fieldBoolDefault(fields, "set_buzzer", false);
        cmd.buzzerOn = fieldBoolDefault(fields, "buzzer_on", false);
        midea::resetMessageId(counter);
        len = cmd.serialize(buf, sizeof(buf));
      } else {
        check(false, name + ": unknown command vector kind");
        continue;
      }
      check(len == expected.size(), name + ": length");
      if (len != expected.size()) continue;
      checkFrameEq(name, toHex(buf, len), fields.at("frame"));
      // QUERY frames except SetProperties, which is CONTROL
      // (command.py:212,387,413,433).
      checkFrameShape(name, buf, len, counter,
                      command == "set_properties" ? midea::kFrameTypeControl : midea::kFrameTypeQuery);
    } else if (fields.count("temperature_type")) {
      midea::GetStateCommand cmd;
      cmd.temperatureType = fieldHex(fields, "temperature_type");
      midea::resetMessageId(counter);
      const size_t len = cmd.serialize(buf, sizeof(buf));
      check(len == expected.size(), name + ": length");
      if (len != expected.size()) continue;
      checkFrameEq(name, toHex(buf, len), fields.at("frame"));
      checkFrameShape(name, buf, len, counter, midea::kFrameTypeQuery);
    } else {
      midea::SetStateCommand cmd;
      cmd.beepOn = fieldBool(fields, "beep_on");
      cmd.powerOn = fieldBool(fields, "power_on");
      cmd.targetTemperature = fieldDouble(fields, "target_temperature");
      cmd.operationalMode = fieldU8(fields, "operational_mode");
      cmd.fanSpeed = fieldU8(fields, "fan_speed");
      cmd.eco = fieldBool(fields, "eco");
      cmd.swingMode = fieldU8(fields, "swing_mode");
      cmd.turbo = fieldBool(fields, "turbo");
      cmd.fahrenheit = fieldBool(fields, "fahrenheit");
      cmd.sleep = fieldBool(fields, "sleep");
      cmd.freezeProtection = fieldBool(fields, "freeze_protection");
      cmd.followMe = fieldBool(fields, "follow_me");
      cmd.purifier = fieldBool(fields, "purifier");
      cmd.targetHumidity = fieldU8(fields, "target_humidity");
      cmd.auxHeat = fieldBool(fields, "aux_heat");
      cmd.forceAuxHeat = fieldBool(fields, "force_aux_heat");
      cmd.independentAuxHeat = fieldBool(fields, "independent_aux_heat");
      midea::resetMessageId(counter);
      const size_t len = cmd.serialize(buf, sizeof(buf));
      check(len == expected.size(), name + ": length");
      if (len != expected.size()) continue;
      checkFrameEq(name, toHex(buf, len), fields.at("frame"));
      checkFrameShape(name, buf, len, counter, midea::kFrameTypeControl);
    }
  }

  // --- Counter semantics (Command._message_id, command.py:190-206) ---
  midea::resetMessageId(0xFE);
  check(midea::nextMessageId() == 0xFF, "counter 0xFE -> 0xFF");
  check(midea::nextMessageId() == 0x00, "counter wraps 0xFF -> 0x00");
  midea::resetMessageId(0x00);
  {
    uint8_t a[midea::kCommandMaxFrameLen], b[midea::kCommandMaxFrameLen];
    midea::GetStateCommand cmd;
    const size_t la = cmd.serialize(a, sizeof(a));
    const size_t lb = cmd.serialize(b, sizeof(b));
    check(la > 3 && lb > 3 && a[la - 3] == 0x01 && b[lb - 3] == 0x02,
          "consecutive serialize() calls consume consecutive ids");
  }

  // --- Buffer edge cases ---
  {
    uint8_t buf[midea::kCommandMaxFrameLen];
    midea::resetMessageId(0x00);
    midea::SetStateCommand cmd;
    // One byte short of what SetState itself needs (frame header + data +
    // message id + CRC8 + checksum), not of the wider frame max.
    constexpr size_t kSetStateFrameLen = midea::kFrameHeaderLen + midea::kSetStateDataLen + 3;
    check(cmd.serialize(buf, kSetStateFrameLen - 1) == 0, "SetState: outCap one short rejected");
    check(cmd.serialize(nullptr, sizeof(buf)) == 0, "null out rejected");
    midea::resetMessageId(0x00);
    const size_t len = cmd.serialize(buf, sizeof(buf));
    check(len != 0, "SetState: exact-size buffer accepted");
  }

  if (gFailures != 0) {
    std::printf("%u checks FAILED\n", gFailures);
    return 1;
  }
  std::printf("commands: all checks passed\n");
  return 0;
}
