// Host test for midea AC response parsing: dispatch (Response.construct),
// StateResponse and CapabilitiesResponse, against golden vectors generated by
// msmart itself (vectors/dispatch.txt, state.txt, state_target.txt,
// capabilities.txt). State frames are classified then parsed from
// frame[10:-2]; capability vectors also cover main+followup merge pairs and
// synthetic single-record reader payloads.
#include "AcState.h"
#include "Frame.h"
#include "Responses.h"

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace {

int hexNibble(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

bool parseHex(const std::string& hex, std::vector<uint8_t>& out) {
  if (hex.size() % 2 != 0) return false;
  out.clear();
  out.reserve(hex.size() / 2);
  for (size_t i = 0; i < hex.size(); i += 2) {
    const int hi = hexNibble(hex[i]);
    const int lo = hexNibble(hex[i + 1]);
    if (hi < 0 || lo < 0) return false;
    out.push_back(static_cast<uint8_t>((hi << 4) | lo));
  }
  return true;
}

using Fields = std::unordered_map<std::string, std::string>;

// Parses the shared vector format: column-0 name, indented `field value`.
std::vector<std::pair<std::string, Fields>> loadVectors(const char* path) {
  std::vector<std::pair<std::string, Fields>> vectors;
  std::ifstream file(path);
  if (!file) {
    std::printf("FAIL: cannot open %s (run from test/host dir)\n", path);
    return vectors;
  }
  std::string line, name;
  Fields fields;
  bool have = false;
  while (std::getline(file, line)) {
    if (line.empty() || line[0] == '#') continue;
    if (line[0] != ' ') {
      if (have) vectors.emplace_back(name, fields);
      name = line;
      fields.clear();
      have = true;
      continue;
    }
    std::istringstream kv(line);
    std::string key, value;
    if (kv >> key >> value) fields[key] = value;
  }
  if (have) vectors.emplace_back(name, fields);
  return vectors;
}

unsigned gFailures = 0;

void check(bool ok, const std::string& what) {
  std::printf("%s %s\n", ok ? "ok  " : "FAIL", what.c_str());
  if (!ok) ++gFailures;
}

// Tri-state expectation: "1"/"0" or "absent".
void checkFlag(const std::string& name, const Fields& fields, const char* key, midea::CapFlag got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  midea::CapFlag want;
  if (it->second == "absent") {
    want = midea::CapFlag::kAbsent;
  } else {
    want = it->second == "1" ? midea::CapFlag::kTrue : midea::CapFlag::kFalse;
  }
  if (got != want) {
    std::printf("FAIL %s: %s got %d want %d\n", name.c_str(), key, static_cast<int>(got), static_cast<int>(want));
    ++gFailures;
  } else {
    check(true, name + ": " + key);
  }
}

void checkBool(const std::string& name, const Fields& fields, const char* key, bool got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  check((it->second == "1") == got, name + ": " + key);
}

void checkU8(const std::string& name, const Fields& fields, const char* key, uint8_t got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  check(static_cast<uint8_t>(std::strtoul(it->second.c_str(), nullptr, 10)) == got, name + ": " + key);
}

// Golden floats are Python repr(); compare with tolerance because both sides
// accumulate int + decimal in double arithmetic.
void checkDouble(const std::string& name, const Fields& fields, const char* key, double got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  const double want = std::strtod(it->second.c_str(), nullptr);
  if (std::fabs(got - want) >= 1e-9) {
    std::printf("FAIL %s: %s got %.6f want %s\n", name.c_str(), key, got, it->second.c_str());
    ++gFailures;
  } else {
    check(true, name + ": " + key);
  }
}

// Optional fields use the literal "none" in vectors when Python returned None.
void checkOptDouble(const std::string& name, const Fields& fields, const char* key, const std::optional<double>& got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  if (it->second == "none") {
    check(!got.has_value(), name + ": " + key + " none");
    return;
  }
  if (!got.has_value()) {
    std::printf("FAIL %s: %s got none want %s\n", name.c_str(), key, it->second.c_str());
    ++gFailures;
    return;
  }
  checkDouble(name, fields, key, *got);
}

void checkOptU8(const std::string& name, const Fields& fields, const char* key, const std::optional<uint8_t>& got) {
  const auto it = fields.find(key);
  if (it == fields.end()) return;
  if (it->second == "none") {
    check(!got.has_value(), name + ": " + key + " none");
    return;
  }
  if (!got.has_value()) {
    std::printf("FAIL %s: %s got none want %s\n", name.c_str(), key, it->second.c_str());
    ++gFailures;
    return;
  }
  check(static_cast<uint8_t>(std::strtoul(it->second.c_str(), nullptr, 10)) == *got, name + ": " + key);
}

void checkAcState(const std::string& name, const Fields& fields, const midea::AcState& s) {
  checkBool(name, fields, "expect_power_on", s.powerOn);
  checkDouble(name, fields, "expect_target", s.targetTemperature);
  checkU8(name, fields, "expect_operational_mode", s.operationalMode);
  checkU8(name, fields, "expect_fan_speed", s.fanSpeed);
  checkU8(name, fields, "expect_swing_mode", s.swingMode);
  checkBool(name, fields, "expect_turbo", s.turbo);
  checkBool(name, fields, "expect_eco", s.eco);
  checkBool(name, fields, "expect_sleep", s.sleep);
  checkBool(name, fields, "expect_fahrenheit", s.fahrenheit);
  checkOptDouble(name, fields, "expect_indoor", s.indoorTemperature);
  checkOptDouble(name, fields, "expect_outdoor", s.outdoorTemperature);
  checkBool(name, fields, "expect_filter_alert", s.filterAlert);
  checkBool(name, fields, "expect_display_on", s.displayOn);
  checkU8(name, fields, "expect_error_code", s.errorCode);
  checkBool(name, fields, "expect_follow_me", s.followMe);
  checkBool(name, fields, "expect_purifier", s.purifier);
  checkBool(name, fields, "expect_aux_heat", s.auxHeat);
  checkBool(name, fields, "expect_independent_aux_heat", s.independentAuxHeat);
  checkOptU8(name, fields, "expect_target_humidity", s.targetHumidity);
  checkBool(name, fields, "expect_freeze_protection", s.freezeProtection);
}

void checkCapabilities(const std::string& name, const Fields& fields, const midea::AcCapabilities& c) {
  checkFlag(name, fields, "expect_anion", c.anion);
  checkFlag(name, fields, "expect_eco", c.eco);
  checkFlag(name, fields, "expect_freeze_protection", c.freezeProtection);
  checkFlag(name, fields, "expect_fahrenheit", c.fahrenheit);
  checkFlag(name, fields, "expect_heat_mode", c.heatMode);
  checkFlag(name, fields, "expect_cool_mode", c.coolMode);
  checkFlag(name, fields, "expect_dry_mode", c.dryMode);
  checkFlag(name, fields, "expect_auto_mode", c.autoMode);
  checkFlag(name, fields, "expect_aux_heat_mode", c.auxHeatMode);
  checkFlag(name, fields, "expect_aux_mode", c.auxMode);
  checkFlag(name, fields, "expect_swing_horizontal", c.swingHorizontal);
  checkFlag(name, fields, "expect_swing_vertical", c.swingVertical);
  checkFlag(name, fields, "expect_fan_silent", c.fanSilent);
  checkFlag(name, fields, "expect_fan_low", c.fanLow);
  checkFlag(name, fields, "expect_fan_medium", c.fanMedium);
  checkFlag(name, fields, "expect_fan_high", c.fanHigh);
  checkFlag(name, fields, "expect_fan_auto", c.fanAuto);
  checkFlag(name, fields, "expect_fan_custom", c.fanCustom);
  checkFlag(name, fields, "expect_humidity_auto_set", c.humidityAutoSet);
  checkFlag(name, fields, "expect_humidity_manual_set", c.humidityManualSet);
  checkFlag(name, fields, "expect_turbo_heat", c.turboHeat);
  checkFlag(name, fields, "expect_turbo_cool", c.turboCool);
  checkFlag(name, fields, "expect_ieco", c.ieco);
  checkFlag(name, fields, "expect_out_silent", c.outSilent);
  checkFlag(name, fields, "expect_self_clean", c.selfClean);
  checkFlag(name, fields, "expect_breeze_away", c.breezeAway);
  checkFlag(name, fields, "expect_breezeless", c.breezeless);
  checkFlag(name, fields, "expect_flash", c.flash);
  checkFlag(name, fields, "expect_rate_select_2_level", c.rateSelect2Level);
  checkFlag(name, fields, "expect_rate_select_5_level", c.rateSelect5Level);
  checkFlag(name, fields, "expect_cascade", c.cascade);
  checkFlag(name, fields, "expect_fresh_air", c.freshAir);
  checkFlag(name, fields, "expect_display_control", c.displayControl);
  if (fields.count("expect_ieco_number")) {
    checkU8(name, fields, "expect_ieco_number", c.iecoNumber);
  }

  const auto tempIt = fields.find("expect_cool_min_temperature");
  if (tempIt != fields.end()) {
    if (tempIt->second == "absent") {
      check(!c.hasTemperatureRanges, name + ": temperature ranges absent");
    } else {
      check(c.hasTemperatureRanges, name + ": temperature ranges present");
      checkDouble(name, fields, "expect_cool_min_temperature", c.coolMin);
      checkDouble(name, fields, "expect_cool_max_temperature", c.coolMax);
      checkDouble(name, fields, "expect_auto_min_temperature", c.autoMin);
      checkDouble(name, fields, "expect_auto_max_temperature", c.autoMax);
      checkDouble(name, fields, "expect_heat_min_temperature", c.heatMin);
      checkDouble(name, fields, "expect_heat_max_temperature", c.heatMax);
      checkBool(name, fields, "expect_decimals", c.temperatureDecimals);
    }
  }
  if (fields.count("expect_additional")) {
    checkBool(name, fields, "expect_additional", c.additionalPending);
  }
}

const char* kindName(midea::ResponseKind kind) {
  switch (kind) {
    case midea::ResponseKind::kInvalid:
      return "invalid";
    case midea::ResponseKind::kNone:
      return "none";
    case midea::ResponseKind::kState:
      return "state";
    case midea::ResponseKind::kCapabilities:
      return "capabilities";
    case midea::ResponseKind::kProperties:
      return "properties";
    case midea::ResponseKind::kPropertiesAck:
      return "properties_ack";
    case midea::ResponseKind::kGroupData:
      return "group_data";
  }
  return "?";
}

// Parses the response payload frame[10:-2] out of a full frame.
const uint8_t* responsePayload(const std::vector<uint8_t>& frame, size_t* len) {
  *len = frame.size() - midea::kFrameHeaderLen - 2;
  return frame.data() + midea::kFrameHeaderLen;
}

void runDispatchVectors() {
  const auto vectors = loadVectors("vectors/dispatch.txt");
  for (const auto& [name, fields] : vectors) {
    std::vector<uint8_t> frame;
    if (!parseHex(fields.at("frame"), frame)) {
      check(false, name + ": malformed frame");
      continue;
    }
    uint8_t group = 0xFF;
    const auto kind = midea::classifyResponse(frame.data(), frame.size(), &group);
    check(std::string(kindName(kind)) == fields.at("expect_kind"),
          name + ": kind " + kindName(kind) + " want " + fields.at("expect_kind"));
    const auto it = fields.find("expect_group");
    if (it != fields.end()) {
      check(group == static_cast<uint8_t>(std::strtoul(it->second.c_str(), nullptr, 10)), name + ": group byte");
    }
  }
}

void runStateVectors() {
  const auto vectors = loadVectors("vectors/state.txt");
  for (const auto& [name, fields] : vectors) {
    std::vector<uint8_t> frame;
    if (!parseHex(fields.at("frame"), frame)) {
      check(false, name + ": malformed frame");
      continue;
    }
    // Classify first: every golden frame must dispatch as StateResponse.
    if (midea::classifyResponse(frame.data(), frame.size()) != midea::ResponseKind::kState) {
      check(false, name + ": classify rejected a state frame");
      continue;
    }
    size_t payloadLen = 0;
    const uint8_t* payload = responsePayload(frame, &payloadLen);
    midea::AcState state;
    if (!midea::parseStateResponse(payload, payloadLen, state)) {
      check(false, name + ": parseStateResponse failed");
      continue;
    }
    check(true, name + ": parsed");
    checkAcState(name, fields, state);
  }
}

void runStateTargetVectors() {
  const auto vectors = loadVectors("vectors/state_target.txt");
  for (const auto& [name, fields] : vectors) {
    std::vector<uint8_t> payload;
    if (!parseHex(fields.at("payload"), payload)) {
      check(false, name + ": malformed payload");
      continue;
    }
    midea::AcState state;
    if (!midea::parseStateResponse(payload.data(), payload.size(), state)) {
      check(false, name + ": parseStateResponse failed");
      continue;
    }
    check(true, name + ": parsed");
    checkAcState(name, fields, state);
  }
}

void runCapabilityVectors() {
  const auto vectors = loadVectors("vectors/capabilities.txt");
  for (const auto& [name, fields] : vectors) {
    // Merge pairs carry two frames and are parsed+merged below.
    if (fields.count("main_frame")) {
      std::vector<uint8_t> mainFrame, followupFrame;
      if (!parseHex(fields.at("main_frame"), mainFrame) || !parseHex(fields.at("followup_frame"), followupFrame)) {
        check(false, name + ": malformed merge frames");
        continue;
      }
      size_t lenA = 0, lenB = 0;
      const uint8_t* a = responsePayload(mainFrame, &lenA);
      const uint8_t* b = responsePayload(followupFrame, &lenB);
      midea::AcCapabilities merged;
      midea::AcCapabilities followup;
      if (!midea::parseCapabilitiesResponse(a, lenA, merged) || !midea::parseCapabilitiesResponse(b, lenB, followup)) {
        check(false, name + ": merge parse failed");
        continue;
      }
      midea::mergeCapabilities(merged, followup);
      check(true, name + ": merged");
      checkCapabilities(name, fields, merged);
      continue;
    }
    // Synthetic single-record payloads bypass the frame layer.
    const std::string hex = fields.count("payload") ? fields.at("payload") : fields.at("frame");
    std::vector<uint8_t> raw;
    if (!parseHex(hex, raw)) {
      check(false, name + ": malformed input");
      continue;
    }
    midea::AcCapabilities caps;
    const bool ok = fields.count("payload") ? midea::parseCapabilitiesResponse(raw.data(), raw.size(), caps) : ([&] {
      if (midea::classifyResponse(raw.data(), raw.size()) != midea::ResponseKind::kCapabilities) {
        return false;
      }
      size_t payloadLen = 0;
      const uint8_t* payload = responsePayload(raw, &payloadLen);
      return midea::parseCapabilitiesResponse(payload, payloadLen, caps);
    })();
    if (!ok) {
      check(false, name + ": parseCapabilitiesResponse failed");
      continue;
    }
    check(true, name + ": parsed");
    checkCapabilities(name, fields, caps);
  }
}

// Properties response vectors: classify, then decode the supported TLVs.
// expect_ieco/expect_out_silent take none|0|1; expect_ieco_failed and
// expect_out_silent_failed pin the result-bit flag when present.
void runPropertyVectors() {
  const auto vectors = loadVectors("vectors/properties.txt");
  for (const auto& [name, fields] : vectors) {
    std::vector<uint8_t> frame;
    if (!parseHex(fields.at("frame"), frame)) {
      check(false, name + ": malformed frame");
      continue;
    }
    const auto kind = midea::classifyResponse(frame.data(), frame.size());
    const auto expectIt = fields.find("expect");
    if (expectIt != fields.end()) {
      // InvalidFrame/InvalidResponseException both surface as kInvalid.
      check(kind == midea::ResponseKind::kInvalid, name + ": kind " + kindName(kind));
      continue;
    }
    if (kind != midea::ResponseKind::kProperties && kind != midea::ResponseKind::kPropertiesAck) {
      // props_notify-style frames: classified but nothing to decode here.
      check(kind == midea::ResponseKind::kNone, name + ": kind " + kindName(kind));
      continue;
    }
    size_t payloadLen = 0;
    const uint8_t* payload = responsePayload(frame, &payloadLen);
    midea::AcPropertyValues values;
    if (!midea::parsePropertyResponse(payload, payloadLen, values)) {
      check(false, name + ": parsePropertyResponse failed");
      continue;
    }
    const auto checkValue = [&](const char* key, bool has, bool on, bool failed) {
      const auto it = fields.find(key);
      if (it == fields.end()) return;
      if (it->second == "none") {
        check(!has, std::string(name) + ": " + key + " none");
        return;
      }
      check(has && on == (it->second == "1"), std::string(name) + ": " + key);
      const auto failIt = fields.find(std::string(key) + "_failed");
      if (failIt != fields.end()) {
        check(failed == (failIt->second == "1"), std::string(name) + ": " + key + "_failed");
      } else {
        check(!failed, std::string(name) + ": " + key + "_failed unset");
      }
    };
    checkValue("expect_ieco", values.hasIeco, values.iecoOn, values.iecoFailed);
    checkValue("expect_out_silent", values.hasOutSilent, values.outSilentOn, values.outSilentFailed);
    checkValue("expect_self_clean", values.hasSelfClean, values.selfCleanOn, values.selfCleanFailed);
    checkValue("expect_breeze_away", values.hasBreezeAway, values.breezeAwayOn, values.breezeAwayFailed);
    checkValue("expect_breezeless", values.hasBreezeless, values.breezelessOn, values.breezelessFailed);
    checkValue("expect_flash", values.hasFlash, values.flashOn, values.flashFailed);
    // 8.6 enum values: expect_<name> takes none|<decimal raw value>.
    const auto checkEnum = [&](const char* key, bool has, uint8_t value, bool failed) {
      const auto it = fields.find(key);
      if (it == fields.end()) return;
      if (it->second == "none") {
        check(!has, std::string(name) + ": " + key + " none");
        return;
      }
      const unsigned want = static_cast<unsigned>(std::strtoul(it->second.c_str(), nullptr, 10));
      check(has && value == want, std::string(name) + ": " + key);
      const auto failIt = fields.find(std::string(key) + "_failed");
      if (failIt != fields.end()) {
        check(failed == (failIt->second == "1"), std::string(name) + ": " + key + "_failed");
      } else {
        check(!failed, std::string(name) + ": " + key + "_failed unset");
      }
    };
    checkEnum("expect_rate_select", values.hasRateSelect, values.rateSelect, values.rateSelectFailed);
    checkEnum("expect_cascade", values.hasCascade, values.cascade, values.cascadeFailed);
    checkEnum("expect_fresh_air", values.hasFreshAir, values.freshAir, values.freshAirFailed);
  }
}

// parsePropertyAck: result bits from a 0xB0 set ack, including bare len-0
// nacks (which parsePropertyResponse would skip) and truncation handling.
void runPropertyAckCases() {
  const auto ack = [](std::initializer_list<uint8_t> payloadBytes, midea::AcPropertyAck& out) {
    const std::vector<uint8_t> payload(payloadBytes);
    return midea::parsePropertyAck(payload.data(), payload.size(), out);
  };
  midea::AcPropertyAck a;
  // payload[0] = response id (ignored), payload[1] = count, then [id LE16, result, len, value].
  check(ack({}, a) == false, "ack: empty payload rejected");
  check(ack({0xB0}, a) == false, "ack: 1-byte payload rejected");

  // Bare len-0 nack for iECO: result bit 0x10 set, no value bytes.
  check(ack({0xB0, 1, 0xE3, 0x00, 0x10, 0x00}, a), "ack: bare len-0 nack parsed");
  check(a.sawIeco && a.iecoFailed, "ack: ieco nack reported failed");
  check(!a.sawOutSilent, "ack: out_silent absent");

  // Bare len-0 ok for out-silent.
  check(ack({0xB0, 1, 0xCD, 0x00, 0x00, 0x00}, a), "ack: bare len-0 ok parsed");
  check(a.sawOutSilent && !a.outSilentFailed, "ack: out_silent ok reported");
  check(!a.sawIeco, "ack: ieco absent");

  // Two TLVs: iECO ok (2-byte value) then out-silent nack (len 0).
  check(ack({0xB0, 2, 0xE3, 0x00, 0x00, 0x02, 0x03, 0x01, 0xCD, 0x00, 0x10, 0x00}, a), "ack: two TLVs parsed");
  check(a.sawIeco && !a.iecoFailed, "ack: ieco ok");
  check(a.sawOutSilent && a.outSilentFailed, "ack: out_silent failed");

  // Truncated second TLV: first decoded, walk stops before the short tail.
  check(ack({0xB0, 2, 0xE3, 0x00, 0x00, 0x02, 0x03, 0x01, 0xCD, 0x00, 0x10}, a), "ack: truncated tail parsed");
  check(a.sawIeco && !a.sawOutSilent, "ack: truncation stops walk after first");

  // Unknown id is skipped without setting any saw flag.
  check(ack({0xB0, 1, 0x99, 0x99, 0x00, 0x01, 0xFF}, a), "ack: unknown id parsed");
  check(!a.sawIeco && !a.sawOutSilent, "ack: unknown id ignored");

  // 8.5 ids: SELF_CLEAN (0x0039) nack with value, BREEZE_AWAY (0x0042) ok,
  // BREEZELESS (0x0018) ok and FLASH (0x0067) failed in one ack.
  check(ack({0xB0, 4,    0x39, 0x00, 0x11, 0x01, 0x01, 0x42, 0x00, 0x00, 0x01,
             0x02, 0x18, 0x00, 0x00, 0x01, 0x01, 0x67, 0x00, 0x10, 0x01, 0x00},
            a),
        "ack: 8.5 ids parsed");
  check(a.sawSelfClean && a.selfCleanFailed, "ack: self_clean failed");
  check(a.sawBreezeAway && !a.breezeAwayFailed, "ack: breeze_away ok");
  check(a.sawBreezeless && !a.breezelessFailed, "ack: breezeless ok");
  check(a.sawFlash && a.flashFailed, "ack: flash failed");

  // Bare len-0 nack for self-clean still reports the failure.
  check(ack({0xB0, 1, 0x39, 0x00, 0x10, 0x00}, a), "ack: self_clean bare len-0 nack parsed");
  check(a.sawSelfClean && a.selfCleanFailed, "ack: self_clean nack failed");
  check(!a.sawBreezeAway && !a.sawBreezeless && !a.sawFlash, "ack: 8.5 siblings absent");

  // 8.6 ids: RATE_SELECT (0x0048) ok, CASCADE (0x0059) nack, FRESH_AIR
  // (0x004B) ok, each carrying their multi-byte values.
  check(ack({0xB0, 3,    0x48, 0x00, 0x00, 0x01, 0x32, 0x59, 0x00, 0x10,
             0x02, 0x01, 0x01, 0x4B, 0x00, 0x00, 0x03, 0x01, 0x28, 0xFF},
            a),
        "ack: 8.6 ids parsed");
  check(a.sawRateSelect && !a.rateSelectFailed, "ack: rate_select ok");
  check(a.sawCascade && a.cascadeFailed, "ack: cascade failed");
  check(a.sawFreshAir && !a.freshAirFailed, "ack: fresh_air ok");

  // 8.8: BUZZER (0x001A) is ack-visible but never decoded (msmart returns
  // None): ok and nack result bits only, and it must not leak into siblings.
  check(ack({0xB0, 1, 0x1A, 0x00, 0x00, 0x01, 0x01}, a), "ack: buzzer ok parsed");
  check(a.sawBuzzer && !a.buzzerFailed, "ack: buzzer ok");
  check(!a.sawIeco && !a.sawFlash && !a.sawFreshAir, "ack: buzzer does not set siblings");
  check(ack({0xB0, 1, 0x1A, 0x00, 0x11, 0x01, 0x00}, a), "ack: buzzer nack parsed");
  check(a.sawBuzzer && a.buzzerFailed, "ack: buzzer failed");
}

// Non-vector edge cases around the length guards.
void runEdgeCases() {
  midea::AcState state;
  {
    const uint8_t shortPayload[17] = {0};
    // Exactly 17 bytes must parse (Python reads payload[16] unconditionally).
    check(midea::parseStateResponse(shortPayload, 17, state), "state: 17-byte payload accepted");
    check(!midea::parseStateResponse(shortPayload, 16, state), "state: 16-byte payload rejected");
    check(!midea::parseStateResponse(nullptr, 40, state), "state: null rejected");
  }
  {
    midea::AcCapabilities caps;
    const uint8_t tiny[2] = {0xB5, 0x00};
    check(midea::parseCapabilitiesResponse(tiny, 2, caps), "caps: count-only payload accepted");
    check(!caps.additionalPending, "caps: no additional byte in count-only payload");
    check(!midea::parseCapabilitiesResponse(tiny, 1, caps), "caps: 1-byte payload rejected");
  }
  // 0xB5 with a non-QUERY frame type must classify as kNone, not kCapabilities.
  {
    const uint8_t frame[] = {0xAA, 0x0F, 0xAC, 0, 0, 0, 0, 0, 0, 0x05, 0xB5, 0x00, 0x00, 0x00};
    uint8_t tail = 0;
    for (size_t i = 1; i < 13; ++i)
      tail = static_cast<uint8_t>(tail + frame[i]);
    // classify only needs a valid frame checksum; patch it in place.
    uint8_t patched[14];
    std::memcpy(patched, frame, sizeof(frame));
    patched[13] = static_cast<uint8_t>(~tail + 1);
    check(midea::classifyResponse(patched, sizeof(patched)) == midea::ResponseKind::kNone,
          "dispatch: 0xB5 with frame type 0x5 ignored");
  }
  // merge: absent src flag must not clear a dst flag; present src overwrites.
  {
    midea::AcCapabilities dst;
    dst.eco = midea::CapFlag::kTrue;
    dst.coolMax = 31.0;
    dst.hasTemperatureRanges = true;
    midea::AcCapabilities src;
    src.eco = midea::CapFlag::kAbsent;
    src.freezeProtection = midea::CapFlag::kFalse;
    midea::mergeCapabilities(dst, src);
    check(dst.eco == midea::CapFlag::kTrue, "merge: absent src flag preserved dst");
    check(dst.freezeProtection == midea::CapFlag::kFalse, "merge: present src flag copied");
    check(dst.coolMax == 31.0, "merge: absent src temp block preserved dst");
  }
}

} // namespace

int main() {
  runDispatchVectors();
  runStateVectors();
  runStateTargetVectors();
  runCapabilityVectors();
  runPropertyVectors();
  runPropertyAckCases();
  runEdgeCases();

  if (gFailures != 0) {
    std::printf("%u checks FAILED\n", gFailures);
    return 1;
  }
  std::printf("responses: all checks passed\n");
  return 0;
}
